# Generated by Django 4.2.7 on 2024-03-25 09:54

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import resume_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("tier", models.CharField(default="free", max_length=255)),
                (
                    "resume_links",
                    models.CharField(
                        blank=True,
                        help_text="Separate links with commas",
                        max_length=100000,
                        null=True,
                    ),
                ),
                ("is_authenticated", models.BooleanField(default=True)),
                ("last_login", models.DateTimeField(auto_now=True)),
                (
                    "unique_words",
                    models.CharField(
                        blank=True,
                        help_text="Separate actions words with commas",
                        max_length=10000000,
                        null=True,
                    ),
                ),
                ("reset_password_code", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=15)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("linkedin_link", models.URLField(blank=True, null=True)),
                ("resume_link", models.URLField(blank=True, null=True)),
                ("github_link", models.URLField(blank=True, null=True)),
                ("website_link", models.URLField(blank=True, null=True)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=resume_app.models.OverwriteStorage(),
                        upload_to=resume_app.models.UserProfile.profile_image_upload_to,
                    ),
                ),
                (
                    "institution",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("major", models.CharField(blank=True, max_length=255, null=True)),
                ("minor", models.CharField(blank=True, max_length=255, null=True)),
                ("start_date", models.DateField(default=datetime.date.today)),
                ("end_date", models.DateField(default=datetime.date.today)),
                (
                    "spoken_languages",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "programming_languages",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "technical_skills",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("leadership", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "degree_type",
                    models.CharField(
                        blank=True,
                        choices=[("Science", "Science"), ("Art", "Art")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_user_profile",
                        to="resume_app.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "city",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        max_length=2,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            django.core.validators.MaxLengthValidator(2),
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(1)]
                    ),
                ),
                (
                    "bullet1",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "bullet2",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "bullet3",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resume_app.account",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_experiences",
                        to="resume_app.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("project_skills", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("bullet1", models.CharField(max_length=255)),
                ("bullet2", models.CharField(max_length=255)),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resume_app.account",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="resume_app.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(default="free", max_length=255)),
                ("forms_remaining", models.IntegerField(default=2)),
                ("forms_filled_on_current_plan", models.IntegerField(default=0)),
                ("total_forms_filled", models.IntegerField(default=0)),
                ("total_cover_letters", models.IntegerField(default=0)),
                ("total_tailored_resumes", models.IntegerField(default=0)),
                (
                    "subscription_ids",
                    models.CharField(
                        blank=True,
                        help_text="subscription_ids seperated by commas",
                        max_length=100000,
                        null=True,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resume_app.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscription_id",
                    models.CharField(blank=True, max_length=100000, null=True),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "subscription_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("subscription_cancel_status", models.BooleanField(default=False)),
                (
                    "subscription_cancel_status_text",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "customer_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "customer_email",
                    models.CharField(blank=True, max_length=100000, null=True),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=100000, null=True),
                ),
                ("price_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "product_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_payments",
                        to="resume_app.account",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="user_payment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_payment",
                to="resume_app.payment",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="user_plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_plan",
                to="resume_app.plan",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="user_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profile_account",
                to="resume_app.userprofile",
            ),
        ),
    ]
