# Generated by Django 4.2.7 on 2024-03-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="is_authenticated",),
        migrations.RemoveField(model_name="account", name="last_login",),
    ]
