# Generated by Django 4.2.7 on 2024-01-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="end_date",
            field=models.DateField(default="2023-12-31"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="institution",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="major",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="minor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="start_date",
            field=models.DateField(default="2023-12-31"),
        ),
    ]
