# Generated by Django 4.2.3 on 2023-07-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_resume_data",
            name="RESUME_LINK",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="user_resume_data",
            name="LINK",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
