# Generated by Django 4.2.7 on 2024-03-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0002_remove_account_is_authenticated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
