# Generated by Django 4.2.3 on 2023-07-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0003_user_resume_data_resume_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_resume_data",
            name="EXPERIENCE1_END_DATE",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user_resume_data",
            name="EXPERIENCE1_START_DATE",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user_resume_data",
            name="EXPERIENCE2_END_DATE",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user_resume_data",
            name="EXPERIENCE2_START_DATE",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user_resume_data",
            name="EXPERIENCE3_END_DATE",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user_resume_data",
            name="EXPERIENCE3_START_DATE",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user_resume_data",
            name="EXPERIENCE4_END_DATE",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user_resume_data",
            name="EXPERIENCE4_START_DATE",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user_resume_data",
            name="EXPERIENCE5_END_DATE",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user_resume_data",
            name="EXPERIENCE5_START_DATE",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user_resume_data",
            name="UNIVERSITY_END_DATE",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user_resume_data",
            name="UNIVERSITY_START_DATE",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
