# Generated by Django 4.2.7 on 2024-01-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0007_delete_test_delete_user_resume_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="work_experiences",
            field=models.ManyToManyField(blank=True, to="resume_app.workexperience"),
        ),
    ]
