# Generated by Django 4.2.7 on 2024-05-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0009_payment_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="github_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="linkedin_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
