# Generated by Django 4.2.7 on 2024-01-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0009_remove_userprofile_work_experiences_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="workexperience", name="user_profile",),
        migrations.AddField(
            model_name="workexperience",
            name="user_profiles",
            field=models.ManyToManyField(
                related_name="work_experiences", to="resume_app.userprofile"
            ),
        ),
    ]
