# Generated by Django 4.2.7 on 2024-07-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0010_alter_userprofile_github_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
