# Generated by Django 4.2.7 on 2024-01-17 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0010_remove_workexperience_user_profile_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="workexperience", name="user_profiles",),
        migrations.AddField(
            model_name="workexperience",
            name="user_profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_experiences",
                to="resume_app.userprofile",
            ),
            preserve_default=False,
        ),
    ]
