# Generated by Django 4.2.7 on 2024-07-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0011_alter_payment_id_alter_project_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workexperience",
            name="currently_working",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="payment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
