# Generated by Django 4.2.7 on 2024-07-23 22:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "resume_app",
            "0012_workexperience_currently_working_alter_payment_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "institution",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("major", models.CharField(blank=True, max_length=255, null=True)),
                ("minor", models.CharField(blank=True, max_length=255, null=True)),
                ("start_date", models.DateField(default=datetime.date.today)),
                ("end_date", models.DateField(default=datetime.date.today)),
                ("current", models.BooleanField(default=False)),
                (
                    "degree_type",
                    models.CharField(
                        blank=True,
                        choices=[("Science", "Science"), ("Art", "Art")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_education",
                        to="resume_app.account",
                    ),
                ),
            ],
        ),
    ]
