# Generated by Django 4.2.7 on 2024-01-17 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0012_alter_workexperience_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workexperience",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_experiences",
                to="resume_app.userprofile",
            ),
        ),
    ]
