# Generated by Django 4.2.7 on 2024-07-23 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0013_education"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="degree_type",),
        migrations.RemoveField(model_name="userprofile", name="end_date",),
        migrations.RemoveField(model_name="userprofile", name="institution",),
        migrations.RemoveField(model_name="userprofile", name="major",),
        migrations.RemoveField(model_name="userprofile", name="minor",),
        migrations.RemoveField(model_name="userprofile", name="start_date",),
    ]
