# Generated by Django 4.2.7 on 2024-01-18 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0014_projects"),
    ]

    operations = [
        migrations.RenameModel(old_name="Projects", new_name="Project",),
    ]
