# Generated by Django 4.2.7 on 2024-01-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0015_rename_projects_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_skills",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="programming_languages",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="spoken_languages",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="technical_skills",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
