# Generated by Django 4.2.7 on 2024-07-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0016_remove_education_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="GPA",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
