# Generated by Django 4.2.7 on 2024-01-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0016_project_project_skills_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile", old_name="link", new_name="linkedin_link",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="github_link",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="leadership",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="resume_link",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
