# Generated by Django 4.2.7 on 2024-01-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0017_rename_link_userprofile_linkedin_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="bullet1",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="bullet2",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workexperience",
            name="bullet1",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workexperience",
            name="bullet2",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workexperience",
            name="bullet3",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
