# Generated by Django 4.2.7 on 2024-07-24 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0017_education_gpa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="current",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="end_date",
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="start_date",
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
