# Generated by Django 4.2.7 on 2024-02-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0018_project_bullet1_project_bullet2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workexperience",
            name="city",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workexperience",
            name="state",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
