# Generated by Django 4.2.7 on 2024-07-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "resume_app",
            "0018_alter_education_current_alter_education_end_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="country",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="degree_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Bachelor of Science", "Bachelor of Science"),
                    ("Bachelor of Art", "Bachelor of Art"),
                    ("Master of Arts", "Master of Arts"),
                    ("Master of Science", "Master of Science"),
                    (
                        "Master of Business Administration",
                        "Master of Business Administration",
                    ),
                    ("Associate of Arts", "Associate of Arts"),
                    ("Associate of Science", "Associate of Science"),
                    (
                        "Associate of Business Administration",
                        "Associate of Business Administration",
                    ),
                    ("Associate of Engineering", "Associate of Engineering"),
                    ("Associate of Nursing", "Associate of Nursing"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
