# Generated by Django 4.2.7 on 2024-02-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0019_workexperience_city_workexperience_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workexperience", old_name="city", new_name="location",
        ),
        migrations.RemoveField(model_name="workexperience", name="state",),
    ]
