# Generated by Django 4.2.7 on 2024-02-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0020_rename_city_workexperience_location_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workexperience", old_name="location", new_name="city",
        ),
        migrations.AddField(
            model_name="workexperience",
            name="state",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
