# Generated by Django 4.2.7 on 2024-02-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0021_rename_location_workexperience_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="degree_type",
            field=models.CharField(
                blank=True,
                choices=[("Science", "Science"), ("Art", "Art")],
                max_length=10,
                null=True,
            ),
        ),
    ]
