# Generated by Django 4.2.7 on 2024-07-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0021_education_coursework"),
    ]

    operations = [
        migrations.RemoveField(model_name="education", name="coursework",),
    ]
