# Generated by Django 4.2.7 on 2024-02-01 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0022_userprofile_degree_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workexperience",
            name="bullet1",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="bullet2",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="bullet3",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="city",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="company_name",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="description",
            field=models.TextField(
                validators=[django.core.validators.MinLengthValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="job_title",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="state",
            field=models.CharField(
                max_length=2,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.MaxLengthValidator(2),
                ],
            ),
        ),
    ]
