# Generated by Django 4.2.7 on 2024-02-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0023_alter_workexperience_bullet1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="city",
            field=models.CharField(default="Edison", max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(default="shf46@rutgers.edu", max_length=254),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(default="Sulemaan", max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="github_link",
            field=models.URLField(
                default="https://www.linkedin.com/in/sulemaan-farooq/"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="institution",
            field=models.CharField(
                blank=True, default="Rutgers", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(default="Farooq", max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="linkedin_link",
            field=models.URLField(
                default="https://www.linkedin.com/in/sulemaan-farooq/"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="major",
            field=models.CharField(
                blank=True, default="computer science", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="minor",
            field=models.CharField(
                blank=True, default="data science", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(default="9174565697", max_length=15),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="resume_link",
            field=models.URLField(
                default="https://www.linkedin.com/in/sulemaan-farooq/"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="state",
            field=models.CharField(default="NJ", max_length=255),
        ),
    ]
