# Generated by Django 4.2.7 on 2024-10-07 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0024_account_educations"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="user_profile",),
        migrations.RemoveField(model_name="userprofile", name="user",),
        migrations.RemoveField(model_name="workexperience", name="user_profile",),
        migrations.AlterField(
            model_name="project",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_projects",
                to="resume_app.account",
            ),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_experiences",
                to="resume_app.account",
            ),
        ),
    ]
