# Generated by Django 4.2.7 on 2024-02-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0024_alter_userprofile_city_alter_userprofile_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="account",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="leadership",
            field=models.CharField(
                blank=True, default="rutgers sports club", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="programming_languages",
            field=models.CharField(
                blank=True,
                default=" R, Java, , Spring Boot Pythonanywhere, React, Ruby",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="spoken_languages",
            field=models.CharField(
                blank=True, default="English, Arabic, Urdu", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="technical_skills",
            field=models.CharField(
                blank=True,
                default="GCP, Springboot, DataDog",
                max_length=255,
                null=True,
            ),
        ),
    ]
