# Generated by Django 4.2.7 on 2024-02-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0025_account_alter_userprofile_leadership_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="tier",
            field=models.CharField(default="basic", max_length=255),
        ),
    ]
