# Generated by Django 4.2.7 on 2024-02-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0026_account_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="tier",
            field=models.CharField(default="free", max_length=255),
        ),
    ]
