# Generated by Django 4.2.7 on 2024-11-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0026_alter_project_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="unique_words",
            field=models.CharField(
                blank=True,
                help_text="Separate action words with commas",
                max_length=10000000,
                null=True,
            ),
        ),
    ]
