# Generated by Django 4.2.7 on 2024-02-10 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0029_freeplan_forms_remaining"),
    ]

    operations = [
        migrations.RemoveField(model_name="freeplan", name="account",),
        migrations.AddField(
            model_name="account",
            name="plan",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="resume_app.freeplan",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="account",
            name="projcts",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="resume_app.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="account",
            name="user_profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="resume_app.userprofile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="account",
            name="work_experience",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="resume_app.workexperience",
            ),
            preserve_default=False,
        ),
    ]
