# Generated by Django 4.2.7 on 2024-02-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "resume_app",
            "0030_remove_freeplan_account_account_plan_account_projcts_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="freeplan",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
