# Generated by Django 4.2.7 on 2024-02-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0031_alter_freeplan_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
