# Generated by Django 4.2.7 on 2024-02-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0032_alter_userprofile_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="projcts",),
        migrations.RemoveField(model_name="account", name="work_experience",),
    ]
