# Generated by Django 4.2.7 on 2024-02-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0033_remove_account_projcts_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="user_profile",),
    ]
