# Generated by Django 4.2.7 on 2024-02-10 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0034_remove_account_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="user_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resume_app.userprofile",
            ),
        ),
    ]
