# Generated by Django 4.2.7 on 2024-02-10 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0035_account_user_profile"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="plan",),
        migrations.RemoveField(model_name="freeplan", name="user_profile",),
        migrations.AddField(
            model_name="freeplan",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resume_app.account",
            ),
        ),
        migrations.AlterField(
            model_name="freeplan",
            name="form_fill_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
