# Generated by Django 4.2.7 on 2024-02-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "resume_app",
            "0036_remove_account_plan_remove_freeplan_user_profile_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="freeplan",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
