# Generated by Django 4.2.7 on 2024-02-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0037_alter_freeplan_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="city",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="userprofile", name="end_date", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile", name="github_link", field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="institution",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="leadership",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile", name="linkedin_link", field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="major",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="minor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="programming_languages",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile", name="resume_link", field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="spoken_languages",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile", name="start_date", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="state",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="technical_skills",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
