# Generated by Django 4.2.7 on 2024-02-10 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0038_alter_userprofile_city_alter_userprofile_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resume_app.account",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_user_profile",
                to="resume_app.account",
            ),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resume_app.account",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="user_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_profile_account",
                to="resume_app.userprofile",
            ),
        ),
    ]
