# Generated by Django 4.2.7 on 2024-02-10 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0039_project_account_userprofile_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="projects",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="resume_app.project",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="work_experience",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_work_experience",
                to="resume_app.workexperience",
            ),
        ),
    ]
