# Generated by Django 4.2.7 on 2024-02-15 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0040_account_projects_account_work_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freeplan",
            name="forms_remaining",
            field=models.IntegerField(default=2),
        ),
        migrations.CreateModel(
            name="BasicPlan",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("forms_remaining", models.IntegerField(default=5)),
                ("payment_link", models.CharField(max_length=10000)),
                ("isMemeber", models.BooleanField(default=False)),
                ("date_of_purchase", models.DateTimeField(null=True)),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resume_app.account",
                    ),
                ),
            ],
        ),
    ]
