# Generated by Django 4.2.7 on 2024-02-19 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0042_basicplan_stripe_checkout_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(default="free", max_length=255)),
                ("forms_remaining", models.IntegerField(default=2)),
                ("forms_filled_on_current_plan", models.IntegerField(default=0)),
                ("total_forms_filled", models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(model_name="freeplan", name="account",),
        migrations.RemoveField(model_name="account", name="projects",),
        migrations.RemoveField(model_name="account", name="work_experience",),
        migrations.DeleteModel(name="BasicPlan",),
        migrations.DeleteModel(name="FreePlan",),
        migrations.AddField(
            model_name="plan",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resume_app.account",
            ),
        ),
    ]
