# Generated by Django 4.2.7 on 2024-02-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "resume_app",
            "0043_plan_remove_freeplan_account_remove_account_projects_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="url_name",
            field=models.CharField(max_length=255),
        ),
    ]
