# Generated by Django 4.2.7 on 2024-02-21 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0044_alter_userprofile_url_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="resume_app.account",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="resume_app.account",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="account_user_profile",
                to="resume_app.account",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="url_name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="resume_app.account",
            ),
        ),
    ]
