# Generated by Django 4.2.7 on 2024-02-21 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0045_alter_plan_account_alter_project_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="user_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profile_account",
                to="resume_app.userprofile",
            ),
        ),
    ]
