# Generated by Django 4.2.7 on 2024-02-22 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0046_alter_account_user_profile"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="url_name",),
        migrations.AlterField(
            model_name="plan",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resume_app.account",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resume_app.account",
            ),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resume_app.account",
            ),
        ),
    ]
