# Generated by Django 4.2.7 on 2024-02-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0047_remove_userprofile_url_name_alter_plan_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="resume_links",
            field=models.CharField(
                blank=True,
                help_text="Separate links with commas",
                max_length=1000,
                null=True,
            ),
        ),
    ]
