# Generated by Django 4.2.7 on 2024-02-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0049_alter_account_resume_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="resume_links",
            field=models.CharField(
                blank=True,
                help_text="Separate links with commas and timestamps",
                max_length=100000,
                null=True,
            ),
        ),
    ]
