# Generated by Django 4.2.7 on 2024-02-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0052_plan_total_cover_letters_plan_total_tailored_resumes"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="subscription_id",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
