# Generated by Django 4.2.7 on 2024-02-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0057_payments"),
    ]

    operations = [
        migrations.RenameModel(old_name="Payments", new_name="Payment",),
    ]
