# Generated by Django 4.2.7 on 2024-02-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0058_rename_payments_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="customer_email",
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
