# Generated by Django 4.2.7 on 2024-02-28 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0059_payment_customer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="end_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="github_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="linkedin_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="resume_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
