# Generated by Django 4.2.7 on 2024-02-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0061_alter_userprofile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(default=1, upload_to=""),
            preserve_default=False,
        ),
    ]
