# Generated by Django 4.2.7 on 2024-02-28 18:57

from django.db import migrations, models
import resume_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0064_alter_userprofile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="website_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=resume_app.models.OverwriteStorage(),
                upload_to=resume_app.models.UserProfile.profile_image_upload_to,
            ),
        ),
    ]
