# Generated by Django 4.2.7 on 2024-03-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0065_userprofile_website_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="account",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="account",
            name="last_login",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
