# Generated by Django 4.2.7 on 2024-03-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0066_account_is_active_account_is_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_authenticated",
            field=models.BooleanField(default=True),
        ),
    ]
