# Generated by Django 4.2.7 on 2024-03-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0067_account_is_authenticated"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="is_active",),
        migrations.RemoveField(model_name="account", name="is_staff",),
    ]
