# Generated by Django 4.2.7 on 2024-03-13 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0068_remove_account_is_active_remove_account_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_payment', to='resume_app.payment'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_plan', to='resume_app.plan'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
