# Generated by Django 4.2.7 on 2024-03-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0069_account_user_payment_account_user_plan_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="email",),
        migrations.AddField(
            model_name="account",
            name="email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
