# Generated by Django 4.2.7 on 2024-03-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0070_remove_userprofile_email_account_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="reset_password_code",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
