# Generated by Django 4.2.7 on 2024-03-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0071_account_reset_password_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="unique_words",
            field=models.CharField(
                blank=True,
                help_text="Separate actions words with commas",
                max_length=10000000,
                null=True,
            ),
        ),
    ]
